name: golangci-lint

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7